import { useState } from "react";
import { Link, Navigate, useLocation, useNavigate } from "react-router";
import { supabase } from "../lib/supabase";
import { useAuth } from "../auth/AuthContext";

function Shell({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) { return <div className="min-h-screen bg-gradient-to-b from-blue-50 via-white to-white px-4 py-12"><div className="mx-auto w-full max-w-md"><Link to="/" className="flex items-center justify-center gap-2 text-lg font-bold text-slate-900"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-blue-600 text-white">⚛</span>Química<span className="text-blue-600">Lab</span></Link><main className="mt-8 rounded-3xl border border-slate-200 bg-white p-7 shadow-xl shadow-blue-100/50"><h1 className="text-2xl font-extrabold text-slate-900">{title}</h1><p className="mt-2 text-sm text-slate-500">{subtitle}</p>{children}</main></div></div>; }
const Field = ({ label, ...props }: React.InputHTMLAttributes<HTMLInputElement> & { label: string }) => <label className="mt-4 block text-sm font-semibold text-slate-700">{label}<input {...props} className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal outline-none transition focus:border-blue-500 focus:ring-2 focus:ring-blue-100" /></label>;
const Message = ({ text, error }: { text: string; error?: boolean }) => <p className={`mt-4 rounded-xl p-3 text-sm ${error ? "bg-red-50 text-red-700" : "bg-green-50 text-green-700"}`}>{text}</p>;

export function LoginPage() { const { user } = useAuth(); const nav = useNavigate(); const location = useLocation(); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false); if(user)return <Navigate to="/dashboard" replace/>; const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setMessage("");const {error}=await supabase.auth.signInWithPassword({email,password});setBusy(false);if(error)setMessage(error.message);else nav((location.state as {from?:string})?.from ?? "/dashboard",{replace:true});}; return <Shell title="Entrar" subtitle="Acesse seu espaço de estudos."><form onSubmit={submit}><Field label="E-mail" type="email" required value={email} onChange={e=>setEmail(e.target.value)} /><Field label="Senha" type="password" required value={password} onChange={e=>setPassword(e.target.value)} />{message&&<Message text={message} error/>}<div className="mt-3 text-right"><Link className="text-sm font-semibold text-blue-600 hover:underline" to="/esqueci-senha">Esqueci minha senha</Link></div><button disabled={busy} className="mt-6 w-full rounded-xl bg-blue-600 py-3 text-sm font-bold text-white hover:bg-blue-700 disabled:opacity-60">{busy?"Entrando...":"Entrar"}</button></form><p className="mt-6 text-center text-sm text-slate-500">Ainda não tem conta? <Link className="font-bold text-blue-600 hover:underline" to="/cadastro">Criar conta</Link></p></Shell>; }
export function RegisterPage() { const { user } = useAuth(); const nav=useNavigate(); const [name,setName]=useState("");const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [confirm,setConfirm]=useState("");const [message,setMessage]=useState("");const [ok,setOk]=useState(false);const [busy,setBusy]=useState(false);if(user)return <Navigate to="/dashboard" replace/>;const submit=async(e:React.FormEvent)=>{e.preventDefault();setMessage("");if(name.trim().length<2)return setMessage("Informe seu nome.");if(password.length<6)return setMessage("A senha precisa ter pelo menos 6 caracteres.");if(password!==confirm)return setMessage("As senhas não coincidem.");setBusy(true);const {data,error}=await supabase.auth.signUp({email,password,options:{data:{name:name.trim()}}});setBusy(false);if(error)return setMessage(error.message);if(data.session)nav("/dashboard");else{setOk(true);setMessage("Conta criada! Confira seu e-mail para confirmar o cadastro.");}};return <Shell title="Criar conta" subtitle="Comece a acompanhar seu aprendizado."><form onSubmit={submit}><Field label="Nome" required value={name} onChange={e=>setName(e.target.value)}/><Field label="E-mail" type="email" required value={email} onChange={e=>setEmail(e.target.value)}/><Field label="Senha" type="password" minLength={6} required value={password} onChange={e=>setPassword(e.target.value)}/><Field label="Confirmar senha" type="password" minLength={6} required value={confirm} onChange={e=>setConfirm(e.target.value)}/>{message&&<Message text={message} error={!ok}/>}<button disabled={busy} className="mt-6 w-full rounded-xl bg-blue-600 py-3 text-sm font-bold text-white hover:bg-blue-700 disabled:opacity-60">{busy?"Criando conta...":"Criar conta"}</button></form><p className="mt-6 text-center text-sm text-slate-500">Já tem uma conta? <Link className="font-bold text-blue-600 hover:underline" to="/login">Entrar</Link></p></Shell>; }
export function ForgotPasswordPage() { const [email,setEmail]=useState("");const [message,setMessage]=useState("");const [error,setError]=useState(false);const [busy,setBusy]=useState(false);const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setMessage("");const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:`${window.location.origin}/login`});setBusy(false);setError(Boolean(error));setMessage(error?.message??"Enviamos as instruções de recuperação para seu e-mail.");};return <Shell title="Recuperar senha" subtitle="Enviaremos um link seguro para redefinir sua senha."><form onSubmit={submit}><Field label="E-mail" type="email" required value={email} onChange={e=>setEmail(e.target.value)}/>{message&&<Message text={message} error={error}/>}<button disabled={busy} className="mt-6 w-full rounded-xl bg-blue-600 py-3 text-sm font-bold text-white hover:bg-blue-700 disabled:opacity-60">{busy?"Enviando...":"Enviar instruções"}</button></form><p className="mt-6 text-center"><Link className="text-sm font-bold text-blue-600 hover:underline" to="/login">Voltar para entrar</Link></p></Shell>; }
