import { useMemo, useState } from "react";

type Drug = { name: string; aliases: string[]; formula: string; mass: string; functions: string[]; pka: string; solubility: string; action: string; structure: string; facts: string[] };
const drugs: Drug[] = [
  { name: "Dipirona", aliases: ["metamizol"], formula: "C13H16N3NaO4S", mass: "333,34 g/mol", functions: ["Sulfonato", "Pirazolona"], pka: "~ 3,7", solubility: "Muito solúvel em água como sal de sódio.", action: "Pró-fármaco analgésico e antipirético; seus metabólitos reduzem a formação de mediadores da dor.", structure: "Anel pirazolona · SO3Na", facts: ["É usada principalmente como sal sódico.", "Possui enxofre e sódio na estrutura.", "Em alguns países, tem uso restrito por risco raro de agranulocitose."] },
  { name: "Paracetamol", aliases: ["acetaminofeno"], formula: "C8H9NO2", mass: "151,16 g/mol", functions: ["Amida", "Fenol"], pka: "9,5 (fenol)", solubility: "Pouco solúvel em água; aumenta com a temperatura.", action: "Analgésico e antipirético de ação central, com modulação de vias relacionadas a prostaglandinas.", structure: "HO—anel benzênico—NHCOCH3", facts: ["Tem um grupo amida e um grupo fenólico.", "Não é um anti-inflamatório potente em doses usuais.", "A massa molar é 151,16 g/mol."] },
  { name: "Ibuprofeno", aliases: [], formula: "C13H18O2", mass: "206,28 g/mol", functions: ["Ácido carboxílico", "Aromático"], pka: "4,9", solubility: "Praticamente insolúvel em água; mais solúvel em meio básico.", action: "Anti-inflamatório não esteroidal: inibe reversivelmente COX-1 e COX-2, reduzindo prostaglandinas.", structure: "Anel benzênico—CH(CH3)—COOH", facts: ["É um ácido fraco.", "A forma S é a mais ativa farmacologicamente.", "Pertence à classe dos derivados do ácido propiônico."] },
  { name: "Amoxicilina", aliases: [], formula: "C16H19N3O5S", mass: "365,40 g/mol", functions: ["β-lactama", "Amida", "Amina", "Ácido carboxílico"], pka: "2,4; 7,4; 9,6", solubility: "Moderadamente solúvel em água; depende do pH.", action: "Antibiótico β-lactâmico que se liga a proteínas ligadoras de penicilina e interrompe a parede celular bacteriana.", structure: "Núcleo penicilina · anel β-lactâmico", facts: ["Contém um anel β-lactâmico reativo.", "É uma aminopenicilina.", "Não atua contra vírus."] },
];

export default function DrugDecoderPage() {
  const [query, setQuery] = useState("Paracetamol");
  const drug = useMemo(() => drugs.find((item) => [item.name, ...item.aliases].some((name) => name.toLowerCase() === query.trim().toLowerCase())) ?? drugs[1], [query]);
  return <div className="min-h-screen bg-slate-50 dark:bg-slate-950"><div className="mx-auto max-w-6xl px-4 py-10 sm:px-6 lg:px-8"><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-wide text-blue-600">Calculadora química</p><h1 className="mt-2 text-3xl font-extrabold text-slate-900">Decodificador de medicamentos</h1><p className="mt-2 text-slate-500">Consulte propriedades químicas de fármacos comuns para fins educativos.</p></div><div className="mt-7 flex max-w-xl gap-2"><input value={query} onChange={(event) => setQuery(event.target.value)} onKeyDown={(event) => event.key === "Enter" && setQuery(query)} placeholder="Digite: Paracetamol" className="min-w-0 flex-1 rounded-lg border border-slate-200 bg-white px-4 py-3 outline-none focus:border-blue-500"/><button onClick={() => setQuery(query)} className="rounded-lg bg-blue-600 px-5 text-sm font-bold text-white">Decodificar</button></div><div className="mt-3 flex flex-wrap gap-2">{drugs.map((item) => <button key={item.name} onClick={() => setQuery(item.name)} className="rounded-full border border-slate-200 bg-white px-3 py-1 text-xs font-semibold text-slate-600 hover:border-blue-300 hover:text-blue-700">{item.name}</button>)}</div><p className="mt-3 text-xs text-slate-500">Quando o nome não está na base demonstrativa, exibimos Paracetamol como referência.</p>
  <div className="mt-7 grid gap-6 lg:grid-cols-[.9fr_1.1fr]"><section className="overflow-hidden rounded-2xl bg-gradient-to-br from-blue-950 to-blue-700 p-7 text-white shadow-sm"><p className="text-sm font-bold text-blue-200">ESTRUTURA MOLECULAR</p><div className="mt-7 grid min-h-56 place-items-center"><div className="relative flex items-center gap-2"><span className="grid h-28 w-28 place-items-center rounded-full border-4 border-blue-200 text-center font-mono text-lg font-bold">{drug.formula}</span><span className="h-1 w-10 bg-cyan-300"/><span className="grid h-16 w-16 place-items-center rounded-full border-2 border-cyan-200 text-xs font-bold">{drug.functions[0]}</span></div></div><p className="text-center font-mono text-sm text-blue-100">{drug.structure}</p></section><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-2xl font-extrabold text-slate-900">{drug.name}</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><Metric label="Fórmula molecular" value={drug.formula} mono/><Metric label="Massa molar" value={drug.mass}/><Metric label="pKa" value={drug.pka}/><Metric label="Solubilidade" value={drug.solubility}/></div><div className="mt-5"><p className="text-xs font-bold text-slate-500">FUNÇÕES QUÍMICAS</p><div className="mt-2 flex flex-wrap gap-2">{drug.functions.map((item) => <span key={item} className="rounded-full bg-blue-50 px-3 py-1 text-sm font-semibold text-blue-700">{item}</span>)}</div></div></section></div>
  <div className="mt-6 grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="font-bold text-slate-900">Mecanismo de ação simplificado</h2><p className="mt-3 leading-relaxed text-slate-600">{drug.action}</p><p className="mt-5 rounded-lg bg-amber-50 p-3 text-xs text-amber-800">Conteúdo educacional. Não substitui orientação de profissionais de saúde ou informação de bula.</p></section><section className="rounded-2xl border border-teal-100 bg-teal-50 p-6"><h2 className="font-bold text-teal-900">Curiosidades químicas</h2><ul className="mt-4 space-y-3 text-sm text-teal-800">{drug.facts.map((fact) => <li key={fact} className="flex gap-2"><span className="font-bold">•</span>{fact}</li>)}</ul></section></div></div></div>;
}

function Metric({ label, value, mono = false }: { label: string; value: string; mono?: boolean }) { return <div className="border-b border-slate-100 pb-3"><p className="text-xs font-bold text-slate-500">{label}</p><p className={`mt-1 text-sm font-semibold text-slate-900 ${mono ? "font-mono" : ""}`}>{value}</p></div>; }
