import { useMemo, useState } from "react";
import { getMixtureResult, mixtureReagents } from "../data/chemicalMixtures";

type HistoryItem = { reagents: string[]; title: string; color: string };

export default function ChemicalMixturesLab({ onBack }: { onBack: () => void }) {
  const [added, setAdded] = useState<string[]>([]);
  const [agitating, setAgitating] = useState(false);
  const [history, setHistory] = useState<HistoryItem[]>([]);
  const result = useMemo(() => getMixtureResult(added), [added]);
  const pHPosition = result.ph === null ? 50 : (result.ph / 14) * 100;
  const liquidHeight = added.length ? Math.min(78, 17 + added.length * 11) : 0;
  const reagentNames = added.map((id) => mixtureReagents.find((reagent) => reagent.id === id)?.name ?? id);

  const addReagent = (id: string) => setAdded((current) => [...current, id]);
  const removeLast = () => setAdded((current) => current.slice(0, -1));
  const clearExperiment = () => {
    if (added.length) setHistory((current) => [{ reagents: reagentNames, title: result.title, color: result.color }, ...current].slice(0, 5));
    setAdded([]);
    setAgitating(false);
  };
  const shake = () => { setAgitating(true); window.setTimeout(() => setAgitating(false), 700); };

  return <div>
    <button onClick={onBack} className="mb-6 text-sm font-semibold text-slate-500 hover:text-teal-600">Voltar ao laboratorio</button>
    <div className="mb-7"><span className="rounded-full border border-teal-200 bg-teal-50 px-3 py-1.5 text-xs font-bold text-teal-700">Nova experiencia</span><h2 className="mt-4 text-3xl font-extrabold text-slate-900">Misturas quimicas</h2><p className="mt-2 max-w-2xl text-slate-500">Adicione reagentes ao bequer e acompanhe efeitos visuais e explicacoes didaticas. pH e temperatura sao valores de simulacao.</p></div>
    <div className="grid gap-6 xl:grid-cols-[290px_minmax(360px,1fr)_320px]">
      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="font-bold text-slate-900">Painel de reagentes</h3><p className="mt-1 text-sm text-slate-500">Escolha uma substancia para adicionar ao recipiente.</p><div className="mt-5 space-y-2">{mixtureReagents.map((reagent) => <div key={reagent.id} className="rounded-xl border border-slate-100 p-3"><div className="flex gap-3"><span className="mt-0.5 h-8 w-8 shrink-0 rounded-full border border-white shadow-sm" style={{ backgroundColor: reagent.color }} /><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><p className="text-sm font-bold text-slate-800">{reagent.name}</p><span className="font-mono text-xs text-slate-500">{reagent.formula}</span></div><p className="mt-1 text-xs leading-relaxed text-slate-500">{reagent.description}</p></div></div><button onClick={() => addReagent(reagent.id)} className="mt-3 w-full rounded-lg border border-teal-200 bg-teal-50 py-1.5 text-xs font-bold text-teal-700 hover:bg-teal-100">Adicionar</button></div>)}</div></section>
      <section className="overflow-hidden rounded-2xl border border-slate-800 bg-gradient-to-b from-slate-950 to-blue-950 p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wide text-blue-200">Area experimental</p><p className="mt-1 text-sm text-white">Bequer de mistura</p></div>{result.heat && <span className="rounded-full border border-orange-300/40 bg-orange-400/20 px-3 py-1 text-xs font-bold text-orange-200">Aquecimento simulado</span>}</div><div className="relative mx-auto mt-6 h-[350px] max-w-sm"><div className="absolute inset-x-8 bottom-8 h-72 overflow-hidden rounded-b-[48px] border-x-4 border-b-4 border-white/80"><div className={`absolute inset-x-0 bottom-0 transition-all duration-700 ${agitating ? "animate-beaker-slosh" : ""}`} style={{ height: `${liquidHeight}%`, backgroundColor: result.color }}><div className="absolute inset-x-0 top-2 h-2 bg-white/30" />{result.precipitate && <div className="absolute inset-x-4 bottom-0 h-12 rounded-t-full bg-sky-200/90"><div className="h-full w-full opacity-70" style={{ backgroundImage: "radial-gradient(#0ea5e9 1px, transparent 1px)", backgroundSize: "8px 8px" }} /></div>}{result.bubbles && Array.from({ length: 9 }, (_, index) => <span key={index} className="absolute h-2.5 w-2.5 animate-bounce rounded-full bg-white/80" style={{ left: `${8 + index * 10}%`, bottom: `${12 + (index % 4) * 15}%`, animationDelay: `${index * 110}ms` }} />)}</div></div><div className="absolute bottom-4 left-1/2 h-3 w-64 -translate-x-1/2 rounded-full bg-black/30" />{result.heat && <div className="absolute right-4 top-8 text-center text-xs font-bold text-orange-200"><span className="block animate-pulse text-2xl">~</span>calor</div>}</div><div className="grid gap-2 sm:grid-cols-3"><button onClick={shake} disabled={!added.length} className="rounded-lg border border-white/20 bg-white/10 px-3 py-2 text-sm font-bold text-white hover:bg-white/20 disabled:opacity-40">Agitar solucao</button><button onClick={removeLast} disabled={!added.length} className="rounded-lg border border-white/20 bg-white/10 px-3 py-2 text-sm font-bold text-white hover:bg-white/20 disabled:opacity-40">Remover ultimo</button><button onClick={clearExperiment} disabled={!added.length} className="rounded-lg bg-white px-3 py-2 text-sm font-bold text-blue-800 hover:bg-blue-50 disabled:opacity-40">Limpar experimento</button></div></section>
      <aside className="space-y-5"><section className="rounded-2xl border border-blue-100 bg-blue-50 p-5"><p className="text-xs font-bold uppercase tracking-wide text-blue-600">Observacoes da experiencia</p><h3 className="mt-2 text-xl font-extrabold text-slate-900">{result.title}</h3><div className="mt-5 space-y-3 border-t border-blue-200 pt-4"><Observation label="Substancias" value={reagentNames.length ? reagentNames.join(" + ") : "Nenhuma"} /><Observation label="Cor observada" value={result.colorName} /><Observation label="Temperatura" value={`${result.temperature} C (simulada)`} /><Observation label="Transformacao" value={result.precipitate ? "Formacao de precipitado" : result.heat ? "Neutralizacao com aquecimento" : "Mudanca visual da mistura"} /></div><div className="mt-5 border-t border-blue-200 pt-4"><div className="flex justify-between text-xs font-bold text-slate-600"><span>ACIDO</span><span>NEUTRO</span><span>BASICO</span></div><div className="relative mt-2 h-2 rounded-full bg-gradient-to-r from-red-500 via-green-400 to-blue-600"><span className="absolute -top-1 h-4 w-4 -translate-x-1/2 rounded-full border-2 border-white bg-slate-900 shadow" style={{ left: `${pHPosition}%` }} /></div><p className="mt-2 text-center text-xs font-semibold text-slate-600">pH aproximado: {result.ph ?? "nao definido"}</p></div></section><section className="rounded-2xl border border-teal-100 bg-teal-50 p-5"><h3 className="font-bold text-teal-900">O que aconteceu?</h3><p className="mt-3 text-sm leading-relaxed text-teal-800">{result.explanation}</p>{result.equation && <div className="mt-4 rounded-lg border border-teal-200 bg-white p-3"><p className="text-xs font-bold text-teal-700">EQUACAO DA REACAO</p><p className="mt-1 break-words font-mono text-sm font-semibold text-slate-800">{result.equation}</p></div>}</section></aside>
    </div>
    <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center justify-between"><div><h3 className="font-bold text-slate-900">Historico da sessao</h3><p className="mt-1 text-sm text-slate-500">Experimentos salvos ao limpar o recipiente nesta sessao.</p></div><span className="text-xs font-semibold text-slate-400">{history.length} registros</span></div>{history.length ? <div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{history.map((item, index) => <div key={`${item.title}-${index}`} className="flex items-center gap-3 rounded-xl bg-slate-50 p-3"><span className="h-8 w-8 rounded-full" style={{ backgroundColor: item.color }} /><div><p className="text-sm font-semibold text-slate-800">{item.title}</p><p className="text-xs text-slate-500">{item.reagents.join(" + ")}</p></div></div>)}</div> : <p className="mt-4 text-sm text-slate-400">Os resultados dos experimentos aparecerao aqui.</p>}</section>
  </div>;
}

function Observation({ label, value }: { label: string; value: string }) { return <div><p className="text-xs font-bold text-slate-500">{label.toUpperCase()}</p><p className="mt-1 text-sm font-semibold text-slate-800">{value}</p></div>; }
